sudo: false
dist: trusty

language: go

go:
  - 1.8.7
  - 1.9.7
  - 1.10.7
  - 1.11.4

install:
  - # Do nothing.

script:
  - go get -d -t -v github.com/die-net/deployer
  - rm -f $GOPATH/src/github.com/coreos/go-etcd/etcd/response.generated.go
  - go get -t -v github.com/die-net/deployer
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
