sudo: false
dist: trusty

language: go

go:
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.3

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
